/**
 * Fallback list of Base UI components
 * Used when GitHub API is unavailable or rate-limited
 * This list contains all 202 components from the Base UI repository
 * Last updated: 2025-10-07 based on docs/reference/generated/*.json
 */
export const FALLBACK_COMPONENT_NAMES: readonly string[] = [
  // Accordion
  "accordion-header",
  "accordion-item",
  "accordion-panel",
  "accordion-root",
  "accordion-trigger",
  // Alert Dialog
  "alert-dialog-backdrop",
  "alert-dialog-close",
  "alert-dialog-description",
  "alert-dialog-popup",
  "alert-dialog-portal",
  "alert-dialog-root",
  "alert-dialog-title",
  "alert-dialog-trigger",
  // Autocomplete
  "autocomplete-root",
  "autocomplete-value",
  // Avatar
  "avatar-fallback",
  "avatar-image",
  "avatar-root",
  // Checkbox
  "checkbox-group",
  "checkbox-indicator",
  "checkbox-root",
  // Collapsible
  "collapsible-panel",
  "collapsible-root",
  "collapsible-trigger",
  // Combobox
  "combobox-arrow",
  "combobox-backdrop",
  "combobox-chip",
  "combobox-chip-remove",
  "combobox-chips",
  "combobox-clear",
  "combobox-collection",
  "combobox-empty",
  "combobox-group",
  "combobox-group-label",
  "combobox-icon",
  "combobox-input",
  "combobox-item",
  "combobox-item-indicator",
  "combobox-item-text",
  "combobox-list",
  "combobox-popup",
  "combobox-portal",
  "combobox-positioner",
  "combobox-root",
  "combobox-row",
  "combobox-selected-value",
  "combobox-status",
  "combobox-trigger",
  "combobox-value",
  // Context Menu
  "context-menu-root",
  "context-menu-trigger",
  // Dialog
  "dialog-backdrop",
  "dialog-close",
  "dialog-description",
  "dialog-popup",
  "dialog-portal",
  "dialog-root",
  "dialog-title",
  "dialog-trigger",
  // Direction Provider
  "direction-provider",
  // Field
  "field-control",
  "field-description",
  "field-error",
  "field-label",
  "field-root",
  "field-validity",
  // Fieldset
  "fieldset-legend",
  "fieldset-root",
  // Form
  "form",
  // Group Collection Provider
  "group-collection-provider",
  // Input
  "input",
  // Menu
  "menu-arrow",
  "menu-backdrop",
  "menu-checkbox-item",
  "menu-checkbox-item-indicator",
  "menu-group",
  "menu-group-label",
  "menu-item",
  "menu-popup",
  "menu-portal",
  "menu-positioner",
  "menu-radio-group",
  "menu-radio-item",
  "menu-radio-item-indicator",
  "menu-root",
  "menu-submenu-root",
  "menu-submenu-trigger",
  "menu-trigger",
  // Menubar
  "menubar",
  // Meter
  "meter-indicator",
  "meter-label",
  "meter-root",
  "meter-track",
  "meter-value",
  // Navigation Menu
  "navigation-menu-arrow",
  "navigation-menu-backdrop",
  "navigation-menu-content",
  "navigation-menu-icon",
  "navigation-menu-item",
  "navigation-menu-link",
  "navigation-menu-list",
  "navigation-menu-popup",
  "navigation-menu-portal",
  "navigation-menu-positioner",
  "navigation-menu-root",
  "navigation-menu-trigger",
  "navigation-menu-viewport",
  // No SSR
  "no-ssr",
  // Number Field
  "number-field-decrement",
  "number-field-group",
  "number-field-increment",
  "number-field-input",
  "number-field-root",
  "number-field-scrub-area",
  "number-field-scrub-area-cursor",
  // Popover
  "popover-arrow",
  "popover-backdrop",
  "popover-close",
  "popover-description",
  "popover-popup",
  "popover-portal",
  "popover-positioner",
  "popover-root",
  "popover-title",
  "popover-trigger",
  // Preview Card
  "preview-card-arrow",
  "preview-card-backdrop",
  "preview-card-popup",
  "preview-card-portal",
  "preview-card-positioner",
  "preview-card-root",
  "preview-card-trigger",
  // Progress
  "progress-indicator",
  "progress-label",
  "progress-root",
  "progress-track",
  "progress-value",
  // Radio
  "radio-group",
  "radio-indicator",
  "radio-root",
  // Scroll Area
  "scroll-area-content",
  "scroll-area-corner",
  "scroll-area-root",
  "scroll-area-scrollbar",
  "scroll-area-thumb",
  "scroll-area-viewport",
  // Select
  "select-arrow",
  "select-backdrop",
  "select-group",
  "select-group-label",
  "select-icon",
  "select-item",
  "select-item-indicator",
  "select-item-text",
  "select-list",
  "select-popup",
  "select-portal",
  "select-positioner",
  "select-root",
  "select-scroll-down-arrow",
  "select-scroll-up-arrow",
  "select-trigger",
  "select-value",
  // Separator
  "separator",
  // Slider
  "slider-control",
  "slider-indicator",
  "slider-root",
  "slider-thumb",
  "slider-track",
  "slider-value",
  // Switch
  "switch-root",
  "switch-thumb",
  // Tabs
  "tabs-indicator",
  "tabs-list",
  "tabs-panel",
  "tabs-root",
  "tabs-tab",
  // Toast
  "toast-action",
  "toast-close",
  "toast-content",
  "toast-description",
  "toast-portal",
  "toast-provider",
  "toast-root",
  "toast-title",
  "toast-viewport",
  // Toggle
  "toggle",
  "toggle-group",
  // Toolbar
  "toolbar-button",
  "toolbar-group",
  "toolbar-input",
  "toolbar-link",
  "toolbar-root",
  "toolbar-separator",
  // Tooltip
  "tooltip-arrow",
  "tooltip-popup",
  "tooltip-portal",
  "tooltip-positioner",
  "tooltip-provider",
  "tooltip-root",
  "tooltip-trigger",
  // Utilities
  "use-render",
] as const;
