export const GITHUB_CONFIG = {
  apiBase: "https://api.github.com/repos/mui/base-ui",
  rawBase: "https://raw.githubusercontent.com/mui/base-ui/master",
  referencePath: "docs/reference/generated",
  examplesPath: "docs/src/app/(public)/(content)/react/components",
} as const;

export const SERVER_CONFIG = {
  name: "base-ui",
  version: "1.0.0-beta.2",
} as const;

export const FETCHER_CONFIG = {
  timeout: 30000,
  retries: 0,
} as const;

export const CACHE_CONFIG = {
  enabled: true,
  ttl: undefined,
} as const;

// Fallback component names for when GitHub API is unavailable
export const FALLBACK_COMPONENT_NAMES: readonly string[] = [
  "accordion-header",
  "accordion-item",
  "accordion-panel",
  "accordion-root",
  "accordion-trigger",
  "alert-dialog-backdrop",
  "alert-dialog-close",
  "alert-dialog-description",
  "alert-dialog-popup",
  "alert-dialog-portal",
  "alert-dialog-root",
  "alert-dialog-title",
  "alert-dialog-trigger",
  "autocomplete-root",
  "autocomplete-value",
  "avatar-fallback",
  "avatar-image",
  "avatar-root",
  "checkbox-group",
  "checkbox-indicator",
  "checkbox-root",
  "collapsible-panel",
  "collapsible-root",
  "collapsible-trigger",
  "combobox-arrow",
  "combobox-backdrop",
  "combobox-chip",
  "combobox-chip-remove",
  "combobox-chips",
  "combobox-clear",
  "combobox-collection",
  "combobox-empty",
  "combobox-group",
  "combobox-group-label",
  "combobox-icon",
  "combobox-input",
  "combobox-item",
  "combobox-item-indicator",
  "combobox-item-text",
  "combobox-popup",
  "combobox-positioner",
  "combobox-portal",
  "combobox-root",
  "combobox-separator",
  "combobox-trigger",
  "combobox-viewport",
  "dialog-backdrop",
  "dialog-close",
  "dialog-description",
  "dialog-popup",
  "dialog-portal",
  "dialog-root",
  "dialog-title",
  "dialog-trigger",
  "field-control",
  "field-description",
  "field-error",
  "field-hint",
  "field-label",
  "field-root",
  "field-validity",
  "menu-arrow",
  "menu-checkbox-item",
  "menu-checkbox-item-indicator",
  "menu-group",
  "menu-group-label",
  "menu-item",
  "menu-popup",
  "menu-positioner",
  "menu-portal",
  "menu-radio-group",
  "menu-radio-item",
  "menu-radio-item-indicator",
  "menu-root",
  "menu-separator",
  "menu-submenu-trigger",
  "menu-trigger",
  "number-field-decrement",
  "number-field-group",
  "number-field-increment",
  "number-field-input",
  "number-field-root",
  "number-field-scrub-area",
  "number-field-scrub-area-cursor",
  "popover-arrow",
  "popover-backdrop",
  "popover-close",
  "popover-description",
  "popover-popup",
  "popover-positioner",
  "popover-portal",
  "popover-root",
  "popover-title",
  "popover-trigger",
  "preview-card-arrow",
  "preview-card-backdrop",
  "preview-card-popup",
  "preview-card-positioner",
  "preview-card-portal",
  "preview-card-root",
  "preview-card-trigger",
  "progress-indicator",
  "progress-root",
  "progress-track",
  "radio-group-indicator",
  "radio-group-root",
  "radio-indicator",
  "radio-root",
  "rating-group-indicator",
  "rating-group-item",
  "rating-group-root",
  "scroll-area-corner",
  "scroll-area-root",
  "scroll-area-scrollbar",
  "scroll-area-thumb",
  "scroll-area-viewport",
  "select-arrow",
  "select-backdrop",
  "select-clear",
  "select-collection",
  "select-group",
  "select-group-label",
  "select-icon",
  "select-item",
  "select-item-indicator",
  "select-item-text",
  "select-popup",
  "select-positioner",
  "select-portal",
  "select-root",
  "select-separator",
  "select-trigger",
  "select-value",
  "select-viewport",
  "slider-control",
  "slider-indicator",
  "slider-output",
  "slider-root",
  "slider-thumb",
  "slider-track",
  "slider-value",
  "switch-root",
  "switch-thumb",
  "tabs-list",
  "tabs-panel",
  "tabs-root",
  "tabs-tab",
  "tabs-tab-indicator",
  "text-field-input",
  "text-field-root",
  "toast-close",
  "toast-description",
  "toast-provider",
  "toast-root",
  "toast-title",
  "toast-trigger",
  "toggle-group-root",
  "toggle-indicator",
  "toggle-root",
  "tooltip-arrow",
  "tooltip-popup",
  "tooltip-positioner",
  "tooltip-portal",
  "tooltip-provider",
  "tooltip-root",
  "tooltip-trigger",
] as const;
